[ia]
type = internetarchive
access_key_id = OxBszwtyyBBleNGI
secret_access_key = GHCJ0VYnhoQFOwwm

[drime]
type = drime
access_token = 29694|XrQ6JtCRzlgNnblHGjf2FHKIOUF0tzuM9k8K9tCC1d9ebf5f

[filen]
type = filen
email = salmon1695@e-record.com
password = 9SBvPDhox0bXTFunQFqnLg-zrSBqvFo_3i42-aXP9g
api_key = Da4n9JecQ4cHWocCCHroid0FITxP5Lpmah-GynOmmh3-n_ezg7iugJawdlY5_DX7NNpLJrsc8nuDp8WQQ81QHbCayVFc15u1BjOGIH7PQtw

[drime2]
type = drime
access_token = 29713|ngM89Bt6TUzN2POLxiGze8h4C4B20ccU1zYejA3bbdd2124f

[drime3]
type = drime
access_token = 29718|NwZMryVxuWfLJeMpJesJPHYClhwKOwMBwtP0oSrE8d345ccd

[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7MYiqo4YiznRVZ24-r_X2JZOOHphFEY2vDu2boKtAFG0uFKgIP0ml4BOpvtCwIIFeZyAperP89eaa3AMeJeVfwS4tFe7QM769Q9CAu9xsddbEBbEZtHcqWqpBBEK-IFp94vg0vk66YVtOWUwpt0Do5fPmN6IegqVQLzWP4o7kOa3Jsfzd_ReT9AJv4cheowe5I1ZwaCgYKAekSARESFQHGX2MiQb_VrQEJcrTTrRbWPDx4TA0206","token_type":"Bearer","refresh_token":"1//0g3yGS0qTwYJRCgYIARAAGBASNwF-L9IrXAy0hu14Lm0ZxSfDDbezTK0wIbwXIVI8pKmP7k5auHJowMwV87y6bDaajRSVf-SUdSs","expiry":"2026-04-02T16:45:28.8087012+05:30","expires_in":3599}
team_drive =

[mega]
type = mega
pass = xa81etWkPBHM2ijUqBZSvJQonRlnt69Fes0fb380bvsyRhC2aMSXXbXE
user = salmon1695@e-record.com
